name: Deploy to GitHub Pages

# main ブランチ の push 時にこのワークフローを実行する
on:
 push:
   branches:
     - main

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
     # main ブランチを取得する
     - name: Checkout
       uses: actions/checkout@v3

     # Node.js のセットアップをする
     - name: Setup Node
       uses: actions/setup-node@v3
       with:
         node-version: 16
         cache: npm

     # ビルドする
     - name: Build
       run: |
          npm ci
          npm run build
          npm run export
          touch out/.nojekyll

     # GitHub Pages にデプロイする
     - name: Deploy
       uses: JamesIves/github-pages-deploy-action@v4
       with:
         branch: gh-pages
         github_token: ${{ secrets.TODO_TUTORIAL_TOKEN }}
         folder: out
